### ISSUE TITLE
No functionality to burn tokens by a user

### ISSUE THREAD

**Issue by TheSmartnik** [ton-blockchain/stablecoin-contract#19]
Currently, the updated jetton_wallet contract doesn't allow to burn tokens by an owner
https://github.com/ton-blockchain/stablecoin-contract/blob/74a0f2c6f44a351dd73c4e74a657e9a9104fcad1/contracts/jetton-wallet.fc#L157-L158

Not sure if it's intended or not. If yes I think README should be updated to reflect this difference between the original contract

**Comment by Dimandinata11** [comment]
22fec6b69e4800ace71cc5fbf0b06f4d36af120a

**Comment by mrppuran** [comment]
Not sure if it's intended or not. If yes I think README should be updated to reflect this difference between the original contract

**Comment by tolya-yanot** [comment]
Only administrator can burn, it's by design
