### ISSUE TITLE
Have you tried without msg_body and msg?

### ISSUE THREAD

**Issue by isopen** [ton-blockchain/stablecoin-contract#22]
I'm not sure if func supports such deep nested cells without using msg_body and msg.
![image](https://github.com/ton-blockchain/stablecoin-contract/assets/7373292/339e90c1-d1b5-4bac-a571-a682d99a64b4)
);
...
Most likely this is bad style and it’s not at all a fact that it will work with func, but if so, then you can do without msg_body and msg.
Comments left in the original code may also be affected.

**Comment by ProgramCrafter** [comment]
What do you mean "won't work"? Compilation error will arise, in a contract that *was already compiled before*?

**Comment by tolya-yanot** [comment]
FunC supports this, the contract is compiled
