### ISSUE TITLE
No ignoring of empty and bounced messages in jetton-minter.fc recv_external function

### ISSUE THREAD

**Issue by dmitretretre** [ton-blockchain/stablecoin-contract#34]
I apologize in advance if there are any errors in my text. English is not my first language.

Critical error in Stablecoin contract
Code repository link:
GitHub - ton-blockchain/stablecoin-contract: https://github.com/ton-blockchain/stablecoin-contract
This repository contains the code for the Stablecoin smart contract in which a critical bug was discovered.

Description:
A critical bug has been discovered in the Stablecoin contract located at https://github.com/ton-blockchain/stablecoin-contract/blob/main/contracts/jetton-minter.fc, a critical error has been discovered that can restore the contract's functionality due to spam of empty and bounced messages.

The essence of the bug:
The error was found in the recv_external function. At the beginning of the function, a condition must be declared to ignore empty and bounced messages. In this case, it is missing.

Attack example:
Attackers load a contract with empty and bounced messages
The contract cannot process so many messages and they begin to accumulate in the blockchain
Using this, the attackers transfer the admin rights to themselves by contract and withdraw money from the contract

Consequences:
This bug can lead to the theft of all funds from the liquidity pool of the Stablecoin contract. This could lead to the devaluation of Stablecoin tokens and loss of user confidence in the platform.

Recommendations:
Update the Stablecoin contract immediately.
Freeze all funds in the liquidity pool.
Conduct an audit of the Stablecoin contract.

User Notification:
Important: All users who interact with the Stablecoin contract are advised to withdraw their funds immediately.

```
() recv_internal(int msg_value, cell in_msg_full, slice in_msg_body) impure {
    slice in_msg_full_slice = in_msg_full.begin_parse();
    int msg_flags = in_msg_full_slice~load_msg_flags();
```

Error:
This function does not ignore empty messages and immediately starts processing messages of all kinds.

Correction:
```
() recv_internal(int msg_value, cell in_msg_full, slice in_msg_body) impure {
    if (in_msg_body.slice_empty?()) { ;; ignore empty messages
        return ();
    }
    slice cs = in_msg_full.begin_parse();
    int flags = cs~load_uint(4);

    if (flags & 1) { ;; ignore all bounced messages
        return ();
    }
```
The correct version ignores all bounced and empty messages.

Other possible fixes:
Use if as a message type check.

Contacts:
Telegram: @smilefromthestreets

**Comment by ProgramCrafter** [comment]
1. Bounced messages **must** be processed in this contract (see line 62) so your suggestion is invalid immediately;
2.  > The contract cannot process so many messages and they begin to accumulate in the blockchain
Using this, the attackers transfer the admin rights to themselves by contract and withdraw money from the contract
    
    How would queue of messages allow that to an attacker? If you have found that contracts' code may be bypassed in some cases, please report the bug to TON Blockchain repo, not to this contract system.

**Comment by tolya-yanot** [comment]
What you wrote makes no sense
