### ISSUE TITLE
Potential error in jettonContentToCell Function of JettonMinter.ts due to Missing storeStringTail Function in Updated Builder.js

### ISSUE THREAD

**Issue by DanGlChris** [ton-blockchain/stablecoin-contract#36]
Description:

There is a possible issue in the `JettonMinter.ts` file related to the `beginCell()` method from the Builder.js library. The current implementation of  `jettonContentToCell` function uses the `storeStringTail` function on the result of `beginCell`, but it seems that the recent update in the Builder.js library has removed or renamed this function. This discrepancy is causing the `jettonContentToCell` function to throw an error.

Error Occurs In:
The error occurs in the `jettonContentToCell` function within the line range 37-48. Additionally, as a consequence, both `jettonMinterConfigToCell` and `jettonMinterConfigFullToCell` functions may produce errors if they receive a configuration where `config.jetton_content` is not an instance of Cell.

![image](https://github.com/ton-blockchain/stablecoin-contract/assets/49105704/5a19e978-1530-4f30-a817-fc77d0a1fb9f)

Impact:
This issue can affect any functionality relying on these methods, possibly leading to unexpected behavior or application crashes during runtime.

Steps To Reproduce:
1. Import required libraries including the updated version of Builder.js without the `storeStringTail` function.
2. Attempt to call the `jettonContentToCell` function using appropriate parameters.

Expected Result:
A valid cell containing the provided jetton content data.

Actual Result:
An error caused by invoking the non-existent `storeStringTail` function on the result of the `beginCell` method.

Proposed Solution:
There are two possible solutions to resolve this issue:

1. Update the codebase to use the latest version of the Builder.js library, making necessary modifications to replace deprecated functions such as `storeStringTail`. 
2. If updating the library is not feasible at present, consider downgrading to a previous stable release which still contains the `storeStringTail` function until further updates can be made safely.

**Comment by DanGlChris** [comment]
Same error with storeMaybeRef().  Builder.js does'nt have this function but storeRefMaybe()
![image](https://github.com/ton-blockchain/stablecoin-contract/assets/49105704/3ecd618d-a0c0-4b3a-9579-59bfb6e143f7)

**Comment by mrppuran** [comment]
Description:

There is a possible issue in the JettonMinter.ts file related to the beginCell() method from the Builder.js library. The current implementation of jettonContentToCell function uses the storeStringTail function on the result of beginCell, but it seems that the recent update in the Builder.js library has removed or renamed this function. This discrepancy is causing the jettonContentToCell function to throw an error.

Error Occurs In:
The error occurs in the jettonContentToCell function within the line range 37-48. Additionally, as a consequence, both jettonMinterConfigToCell and jettonMinterConfigFullToCell functions may produce errors if they receive a configuration where config.jetton_content is not an instance of Cell.

**Comment by ProgramCrafter** [comment]
This bug report is based on an invalid assumption: that the code uses `Builder.js` (when in fact it uses `@ton/core`'s type Builder).

**Comment by ProgramCrafter** [comment]
> Same type of error with while creating const mintMsg. Builder.js doesn't have the function storeMaybeRef(); instead, it has the function storeRefMaybe().

And this may be true, actually! I cannot find `storeMaybeRef()` in [latest `@ton/core` version](https://unpkg.com/browse/@ton/core@0.56.3/dist/boc/Builder.js).
