### ISSUE TITLE
Potential problem with getRandomInt

### ISSUE THREAD

**Issue by grannnsacker** [ton-blockchain/stablecoin-contract#41]
Hello, I want to apologize right away for my speech. English is not my native language. 
![image](https://github.com/ton-blockchain/stablecoin-contract/assets/73748679/1bbd0f80-686d-49ec-9849-cfa571a055a8) (pict 1)
Math.random() returns a number in the range [0;1). In the getRandomInt method, you round the resulting number using Math.round. With a sufficiently large number obtained from Math.random, getRandomInt can return a number equal to max. Example in JettonWallet.spec.ts (pict 2)
![image](https://github.com/ton-blockchain/stablecoin-contract/assets/73748679/a433bc3c-92e8-4bb5-b20e-7d9ee62105e6)
Proofs (pict 3)
![image](https://github.com/ton-blockchain/stablecoin-contract/assets/73748679/844b809b-5e2a-4121-bf76-f01846c5e611)

if I really helped in any way, my telegram @grannsacker

**Comment by tolya-yanot** [comment]
This is code of tests, not code of smart contract. Max value is also valid for tests
