### ISSUE TITLE
Error handling , vulnerable crashes

### ISSUE THREAD

**Issue by abdallhfattah** [ton-blockchain/stablecoin-contract#43]
There is no error handling in the code.
![image](https://github.com/ton-blockchain/stablecoin-contract/assets/90351844/1305b87e-1cd6-4f0d-8c13-18a58eab1828)

librarian.func <- file

**Comment by ProgramCrafter** [comment]
How exactly gas calculation is incorrect? Also please note that `to_reserve` value is spent gradually over time, not on publishing the library.

**Comment by tolya-yanot** [comment]
What's the issue?
