### ISSUE TITLE
jetton-minter.fc burn_notification

### ISSUE THREAD

**Issue by mahdihoseini123** [ton-blockchain/stablecoin-contract#64]
I think according to line 113, burn can be done by someone other than the admin, and this is inconsistent with jetton-wallet.fc line 14, as well as other codes that contain burn instructions, such as line 222 of jetton-wallet. fc means ( burn_jettons(in_msg_body, sender_address, msg_value);)
An instruction should be added to it that only the admin can burn
and remove the instructions for burning by the sender

Thank you

**Comment by tolya-yanot** [comment]
Only administrator can burn, it's by design.

There is no mention in the repository that user can burn.
